"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { getAnimalImages } from "@/lib/animalImageHelper";

type Status = "pending" | "approved" | "rejected";
type RequestItem = { id:string; name:string; species:string; image:string; date:string; shelter:string; status:Status; reason?:string; careTime?:string; budget?:number; family?:number; adoptionReason?:string; user?:{ accommodation_type?:string; address?:string; province?:string; pet_permission?:boolean; residence_note?:string; animal_count?:number } | null };
const statusInfo = { pending:{label:"รอการอนุมัติ", icon:"fa-hourglass-half", tone:"bg-amber-50 text-amber-700 border-amber-200"}, approved:{label:"อนุมัติแล้ว",icon:"fa-circle-check",tone:"bg-emerald-50 text-emerald-700 border-emerald-200"},rejected:{label:"ไม่อนุมัติ",icon:"fa-circle-xmark",tone:"bg-rose-50 text-rose-700 border-rose-200"} };
const careLabels: Record<string,string> = { under_2:"น้อยกว่า 2 ชั่วโมง", "2_4":"2–4 ชั่วโมง", "4_6":"4–6 ชั่วโมง", over_6:"มากกว่า 6 ชั่วโมง" };
const filters: { value:"all"|Status; label:string }[] = [{value:"all",label:"ทั้งหมด"},{value:"pending",label:"รอการอนุมัติ"},{value:"approved",label:"อนุมัติแล้ว"},{value:"rejected",label:"ไม่อนุมัติ"}];
const toStatus=(value:string):Status=>value==="อนุมัติ"?"approved":value==="ปฏิเสธ"?"rejected":"pending";

export default function AdoptionRequestsPage() {
  const [requests,setRequests]=useState<RequestItem[]>([]); const [filter,setFilter]=useState<"all"|Status>("all"); const [selected,setSelected]=useState<RequestItem|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [busy,setBusy]=useState("");
  function load() { setLoading(true); setError(""); fetch("/api/adoptions").then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);setRequests((data.requests||[]).map((row:any)=>{const animal=Array.isArray(row.animals)?row.animals[0]:row.animals;const shelter=Array.isArray(animal?.shelters)?animal.shelters[0]:animal?.shelters;return {id:row.match_id,name:animal?.name||"สัตว์ที่เลือก",species:animal?.species||"",image:getAnimalImages(animal?.image_url)[0],date:row.start_date,shelter:shelter?.shelter_name||"ศูนย์พักพิง",status:toStatus(row.match_status),reason:row.rejection_reason||undefined,careTime:row.care_time,budget:row.monthly_budget,family:row.family_members,adoptionReason:row.adoption_reason,user:row.users||null}}));}).catch((cause:Error)=>setError(cause.message||"ไม่สามารถอ่านสถานะคำขอได้")).finally(()=>setLoading(false)); }
  useEffect(()=>{load()},[]);
  const visible=useMemo(()=>requests.filter(request=>filter==="all"||request.status===filter),[requests,filter]);
  async function cancel(request:RequestItem) { if(!window.confirm(`ยกเลิกคำขอของ ${request.name} ใช่ไหม?`)) return; setBusy(request.id); const response=await fetch(`/api/adoptions?matchId=${request.id}`,{method:"DELETE"});const data=await response.json();if(!response.ok)setError(data.error||"ยกเลิกคำขอไม่สำเร็จ");else {setRequests(previous=>previous.filter(item=>item.id!==request.id));setSelected(null);}setBusy(""); }
  return <main className="min-h-screen bg-[#FCFAF8] px-5 py-10 text-[#44403C]"><div className="mx-auto max-w-5xl"><Link href="/profile" className="text-sm text-[#C07055] hover:underline">← กลับไปโปรไฟล์ของฉัน</Link><header className="mt-8"><p className="text-sm text-[#C07055]">ทุกคำขอ คือโอกาสของบ้านหลังใหม่</p><h1 className="font-mali text-3xl font-semibold sm:text-4xl">สถานะคำขอรับเลี้ยง <span>📝</span></h1><p className="mt-2 text-sm text-stone-500">ติดตามคำขอและผลการพิจารณาจากเจ้าหน้าที่</p></header>
    {error&&<div className="mt-6 rounded-2xl border border-rose-100 bg-rose-50 px-5 py-4 text-sm text-rose-700">{error}</div>}
    <div className="mt-7 flex flex-wrap gap-2">{filters.map(item=>{const count=requests.filter(request=>item.value==="all"||request.status===item.value).length;return <button key={item.value} onClick={()=>setFilter(item.value)} className={"rounded-full border px-4 py-2 text-sm transition "+(filter===item.value?"border-[#E29578] bg-[#E29578] text-white shadow-sm":"border-stone-200 bg-white text-stone-500")}><span>{item.label}</span><b className={"ml-2 rounded-full px-2 py-0.5 text-xs "+(filter===item.value?"bg-white/20":"bg-stone-100")}>{count}</b></button>})}</div>
    {loading?<p className="py-20 text-center text-stone-500">กำลังโหลดคำขอ…</p>:visible.length===0?<section className="mt-7 rounded-3xl border border-dashed border-[#E7D4C9] bg-white p-12 text-center"><span className="text-4xl">🐾</span><h2 className="mt-3 font-mali text-2xl">ยังไม่มีคำขอในหมวดนี้</h2><p className="mt-2 text-sm text-stone-500">เมื่อส่งคำขอแล้ว สถานะจะแสดงตรงนี้</p><Link href="/cases" className="mt-5 inline-block rounded-full bg-[#E29578] px-5 py-3 text-sm text-white">พบกับน้องที่รอบ้าน</Link></section>:<section className="mt-7 grid gap-5">{visible.map(request=>{const state=statusInfo[request.status];return <article key={request.id} className="flex flex-col gap-5 rounded-3xl border border-stone-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center"><img src={request.image} alt={request.name} className="h-24 w-24 rounded-2xl bg-[#FDF0EB] object-cover"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><h2 className="font-itim text-3xl">{request.name}</h2><span className="rounded-full bg-[#FDF0EB] px-3 py-1 text-xs text-[#A07866]">{request.species}</span></div><p className="mt-2 text-sm text-stone-500">📍 {request.shelter}</p><p className="mt-1 text-xs text-stone-400">ส่งคำขอเมื่อ {new Date(request.date).toLocaleDateString("th-TH")}</p><span className={"mt-3 inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs "+state.tone}><i className={"fa-solid "+state.icon}/>{state.label}</span>{request.reason&&<p className="mt-3 rounded-xl bg-rose-50 p-3 text-xs text-rose-700"><b>เหตุผล: </b>{request.reason}</p>}</div><div className="flex shrink-0 gap-2 sm:flex-col"><button onClick={()=>setSelected(request)} className="rounded-xl border border-stone-200 bg-white px-4 py-2 text-sm text-stone-600 hover:border-[#E29578]">ดูรายละเอียด</button>{request.status==="pending"&&<button onClick={()=>cancel(request)} disabled={busy===request.id} className="rounded-xl bg-[#FFF0ED] px-4 py-2 text-sm text-[#B94D50] disabled:opacity-60">{busy===request.id?"กำลังยกเลิก…":"ยกเลิกคำขอ"}</button>}</div></article>})}</section>}
    {selected&&<DetailModal request={selected} busy={busy===selected.id} onClose={()=>setSelected(null)} onCancel={()=>cancel(selected)}/>}
  </div></main>;
}

function DetailModal({request,busy,onClose,onCancel}:{request:RequestItem;busy:boolean;onClose:()=>void;onCancel:()=>void}) { const state=statusInfo[request.status]; const address=[request.user?.address,request.user?.province].filter(Boolean).join(" · "); return <div className="fixed inset-0 z-[100] grid place-items-center bg-[#251C1A]/55 p-4"><section role="dialog" aria-modal="true" aria-label="รายละเอียดคำขอ" className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-[28px] bg-[#FCFAF8] p-6 shadow-2xl sm:p-8"><div className="flex items-start gap-4 border-b border-[#E7E5E4] pb-5"><img src={request.image} alt={request.name} className="h-16 w-16 rounded-full object-cover"/><div className="min-w-0 flex-1"><p className="text-sm text-[#C07055]">คำขอรับเลี้ยง</p><h2 className="font-itim text-3xl">น้อง{request.name}</h2><span className={"mt-1 inline-flex rounded-full border px-3 py-1 text-xs "+state.tone}>{state.label}</span></div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-full bg-[#FDF0EB] text-xl">×</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Summary icon="fa-building" label="ศูนย์ดูแล" value={request.shelter}/><Summary icon="fa-calendar" label="วันที่ส่งคำขอ" value={new Date(request.date).toLocaleDateString("th-TH")}/></div><section className="mt-6 rounded-2xl border border-[#F1DDD3] bg-white p-5"><h3 className="font-mali text-lg">🏠 บ้านและความพร้อม</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><Summary label="ที่พัก" value={request.user?.accommodation_type}/><Summary label="ที่พักอนุญาตให้เลี้ยงสัตว์" value={request.user?.pet_permission?"อนุญาตแล้ว ✓":"ยังไม่แน่ใจ"}/><Summary label="เวลาดูแลต่อวัน" value={careLabels[request.careTime||""]||request.careTime}/><Summary label="งบดูแลต่อเดือน" value={request.budget?request.budget.toLocaleString("th-TH")+" บาท":"-"}/><Summary label="สมาชิกในครอบครัว" value={request.family?request.family+" คน":"ไม่ระบุ"}/><Summary label="สัตว์เลี้ยงที่มีอยู่" value={request.user?.animal_count===undefined?"ไม่ระบุ":request.user.animal_count+" ตัว"}/></div>{address&&<div className="mt-4 rounded-xl bg-[#FFF8F5] p-4"><p className="text-xs text-stone-400">ที่อยู่</p><p className="mt-1 text-sm">📍 {address}</p></div>}</section>{request.adoptionReason&&<section className="mt-5 rounded-2xl bg-[#FFF8F5] p-5"><p className="font-mali text-base">💗 เหตุผลที่อยากรับเลี้ยง</p><p className="mt-2 text-sm leading-7 text-stone-600">{request.adoptionReason}</p></section>}{request.reason&&<section className="mt-5 rounded-2xl bg-rose-50 p-5 text-rose-700"><p className="font-mali">เหตุผลที่ไม่อนุมัติ</p><p className="mt-2 text-sm">{request.reason}</p></section>}{request.status==="pending"&&<button onClick={onCancel} disabled={busy} className="mt-6 w-full rounded-2xl bg-[#FFF0ED] py-3 text-sm text-[#B94D50] disabled:opacity-60">{busy?"กำลังยกเลิกคำขอ…":"ยกเลิกคำขอนี้"}</button>}</section></div>; }
function Summary({icon,label,value}:{icon?:string;label:string;value:unknown}){return <div className="rounded-xl bg-[#FCFAF8] p-3"><p className="text-xs text-stone-400">{icon&&<i className={"mr-1 fa-solid "+icon}/>} {label}</p><p className="mt-1 text-sm text-[#44403C]">{String(value||"-")}</p></div>}
